#!/usr/bin/env bash
set -euo pipefail

if [ "$(basename "$PWD")" != "spitfire" ]; then
	echo "Must be run from the project root"
	exit 1
fi

if ! command -v op >/dev/null 2>&1; then
	echo "op command (1Password) CLI is not installed"
	exit 1
fi

keystore_properties="$PWD/android/keystore.properties"
cat <<EOF >"$keystore_properties"
storeFile=$PWD/android/keystore.jks
storePassword=$(op read 'op://Personal/Android Keystore/Keystore password')
keyAlias=BaftekKey_Spitfire
keyPassword=$(op read 'op://Personal/Android Keystore/Password for key BaftekKey_Spitfire')
EOF

op document get \
	--force \
	--vault Personal \
	--out-file android/keystore.jks \
	"Android keystore"

echo "$keystore_properties"
