default_platform(:ios)

platform :ios do
  app_store_connect_api_key(
    key_id: "553H6VCHPC",
    issuer_id: "ff222ec2-322e-44a6-b28b-a183bbdd16e5",
    key_filepath: ENV["APP_STORE_CONNECT_API_KEY_P8_PATH"],
    in_house: false,
  )

  # build_number = get_new_build_number(
  #   bundle_identifier: ENV["APP_BUNDLE_ID"],
  #   package_name: ENV["APP_PACKAGE_NAME"],
  #   google_play_json_key_path: ENV["GOOGLE_PLAY_JSON_KEY_PATH"],
  #   firebase_json_key_path: ENV["FIREBASE_JSON_KEY_PATH"],
  #   firebase_app_ios: ENV["FIREBASE_APP_IOS"],
  #   firebase_app_android: ENV["FIREBASE_APP_ANDROID"],
  # ).to_s
  
  # build_name = get_new_build_name()

  # File.write("../robovm.properties", "app.build=#{build_number}\n", mode: "a")
  # File.write("../robovm.properties", "app.version=#{build_name}\n", mode: "a")
  
  desc "Upload a new build to Firebase App Distribution"
  lane :distribute do
    if is_ci
      setup_ci
    end

    firebase_app_distribution_get_udids(
      app: ENV["FIREBASE_APP_IOS"],
      output_file: 'firebase_devices.txt',
      service_credentials_file: ENV["FIREBASE_JSON_KEY_PATH"],
    )

    register_devices(
      devices_file: 'firebase_devices.txt',
    )

    match(
        type: "adhoc",
        readonly: false,
        force_for_new_devices: true,
    )

    gradle(
      task: "robovmArchive",
      project_dir: ".."
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_IOS"],
      groups: "core-team",
      ipa_path: "build/robovm/IOSLauncher.ipa",
      service_credentials_file: ENV["FIREBASE_JSON_KEY_PATH"],
    )
  end

  desc "Upload a new release build to App Store"
  lane :prod do
    app_bundle_id = ENV["APP_BUNDLE_ID"]
    profile_name = "match AppStore #{app_bundle_id}"

    if is_ci
      setup_ci
    end

    sync_code_signing(
      type: "appstore",
      readonly: false,
    )

    ENV["SPITFIRE_APP_STORE"] = "true"
    gradle(
      task: "robovmArchive",
      project_dir: ".."
    )

    upload_to_app_store(
      force: true,
      precheck_include_in_app_purchases: false,
      skip_screenshots: true,
      skip_metadata: true,
      ipa: "build/robovm/IOSLauncher.ipa"
    )
  end
end
