default_platform(:ios)
require 'base64'

platform :ios do
  app_store_connect_api_key(
    key_id: ENV.fetch('APP_STORE_CONNECT_KEY_ID'),
    issuer_id: ENV.fetch('APP_STORE_CONNECT_ISSUER_ID'),
    key_filepath: ENV.fetch('APP_STORE_CONNECT_P8_KEY_PATH'),
    in_house: false
  )

  build_number = get_new_build_number(
    bundle_identifier: ENV.fetch('APP_BUNDLE_ID'),
    package_name: ENV.fetch('APP_PACKAGE_NAME'),
    google_play_json_key_path: ENV.fetch('GOOGLE_PLAY_JSON_KEY_PATH'),
    firebase_json_key_path: ENV.fetch('FIREBASE_JSON_KEY_PATH'),
    firebase_app_ios: ENV.fetch('FIREBASE_APP_ID_IOS'),
    firebase_app_android: ENV.fetch('FIREBASE_APP_ID_ANDROID')
  ).to_s

  ENV['MATCH_GIT_BASIC_AUTHORIZATION'] = Base64.strict_encode64(
    "#{ENV.fetch('GITHUB_USERNAME')}:#{ENV.fetch('GITHUB_PAT')}"
  )

  build_name = get_new_build_name

  File.write('../robovm.properties', "app.build=#{build_number}\n", mode: 'a')
  File.write('../robovm.properties', "app.version=#{build_name}\n", mode: 'a')

  desc 'Upload a new build to Firebase App Distribution'
  lane :distribute do
    setup_ci if is_ci

    firebase_app_distribution_get_udids(
      app: ENV.fetch('FIREBASE_APP_ID_IOS'),
      output_file: 'firebase_devices.txt',
      service_credentials_file: ENV.fetch('FIREBASE_JSON_KEY_PATH')
    )

    register_devices(
      devices_file: 'firebase_devices.txt'
    )

    sync_code_signing(
      type: 'adhoc',
      readonly: false,
      force_for_new_devices: true
    )

    gradle(
      task: 'robovmArchive',
      project_dir: '..'
    )

    firebase_app_distribution(
      app: ENV.fetch('FIREBASE_APP_ID_IOS'),
      groups: 'core-team',
      ipa_path: 'build/robovm/IOSLauncher.ipa',
      service_credentials_file: ENV.fetch('FIREBASE_JSON_KEY_PATH')
    )
  end

  desc 'Upload a new release build to App Store'
  lane :prod do
    setup_ci if is_ci

    sync_code_signing(
      type: 'appstore',
      readonly: false
    )

    ENV['SPITFIRE_APP_STORE'] = 'true'
    gradle(
      task: 'robovmArchive',
      project_dir: '..'
    )

    upload_to_app_store(
      force: true,
      precheck_include_in_app_purchases: false,
      skip_screenshots: true,
      skip_metadata: true,
      ipa: 'build/robovm/IOSLauncher.ipa'
    )
  end
end
