default_platform(:android)

require_relative "../../tools/get_new_build_number.rb"

platform :android do    
  build_number = get_new_build_number(
    package_name: ENV["APP_PACKAGE_NAME"],
    google_play_json_key_path: ENV["GOOGLE_PLAY_JSON_KEY_PATH"],
  ).to_s
  
  desc "Deploy a new internal version to Google Play"
  lane :internal do
    build_android_app(
      task: "bundleRelease",
      properties: {
        "android.injected.version.code" => build_number,
      }
    )

    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      json_key: ENV["GOOGLE_PLAY_JSON_KEY_PATH"],
    )
  end
end
