default_platform(:android)

platform :android do
  desc "Deploy a new beta version to Google Play"
  lane :beta do
    gradle(
      task: "clean bundleRelease",
      project_dir: '..',
    )

    upload_to_play_store(
      track: "beta",
    )
  end

  desc "Deploy a new production version to the Google Play"
  lane :prod do
    gradle(
      task: "clean bundleRelease",
      project_dir: '..',
    )

    upload_to_play_store
  end
end
