name: Distribute to testers

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install fastlane
        run: |
          gem install bundler
          cd android
          bundle install

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create keystore.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/keystore.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/keystore.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/keystore.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/keystore.properties

      - name: Download key.json (for Google Play Android Developer)
        id: firebase_key
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: key.json
          encodedString: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_BASE64 }}

      - name: fastlane android beta
        run: cd android && bundle exec fastlane beta
