name: deploy prod

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: macos-latest

    env:
      APP_BUNDLE_ID: pl.baftek.spitfire
      APP_PACKAGE_NAME: pl.baftek.spitfire
      FIREBASE_APP_IOS: 1:694460082561:ios:21c308ba674a0c96942080
      FIREBASE_APP_ANDROID: 1:694460082561:android:6e7163746a6cf91e

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.0"
          bundler-cache: true

      - name: Install fastlane
        run: |
          gem install bundler
          cd android && bundle install
          cd ..
          cd ios && bundle install

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Download Android keystore
        id: download_android_keystore
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create keystore.properties
        run: |
          echo "storeFile=${{ steps.download_android_keystore.outputs.filePath }}" > android/keystore.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/keystore.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/keystore.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/keystore.properties

      # Apple (App Store and match)
      - name: Create App Store Connect API key
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > ${{ runner.temp }}/key.p8
          echo "APP_STORE_CONNECT_API_KEY_P8_PATH=${{ runner.temp }}/key.p8" >> $GITHUB_ENV

      - name: Create Personal Access Token to access bartekpacia/certificates
        run: echo "MATCH_GIT_BASIC_AUTHORIZATION=${{ secrets.PERSONAL_ACCESS_TOKEN_BASE64 }}" >> $GITHUB_ENV

      - name: Create MATCH_PASSWORD
        run: echo "MATCH_PASSWORD=${{ secrets.MATCH_PASSWORD }}" >> $GITHUB_ENV

      # Firebase
      - name: Download Firebase JSON key (for App Distribution)
        id: firebase_key
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: firebase_key.json
          encodedString: ${{ secrets.GOOGLE_SERVICES_FIREBASE_BASE64 }}

      - name: Set FIREBASE_JSON_KEY_PATH (for App Distribution)
        run: echo "FIREBASE_JSON_KEY_PATH=${{ steps.firebase_key.outputs.filePath }}" >> $GITHUB_ENV

      # Google Play
      - name: Download Google Play JSON key (for Google Play Android Developer)
        id: google_play_android_developer_key
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: google_play_android_developer_key.json
          encodedString: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_BASE64 }}

      - name: Set GOOGLE_PLAY_JSON_KEY_PATH (for Google Play Android Developer)
        run: echo "GOOGLE_PLAY_JSON_KEY_PATH=${{ steps.google_play_android_developer_key.outputs.filePath }}" >> $GITHUB_ENV

      - name: Validate GOOGLE_PLAY_JSON_KEY_PATH
        run: fastlane run validate_play_store_json_key json_key:"$GOOGLE_PLAY_JSON_KEY_PATH"

      - name: fastlane ios prod
        run: |
          echo "SPITFIRE_APP_STORE=true" >> $GITHUB_ENV
          cd ios && bundle exec fastlane prod

      - name: fastlane android internal
        run: cd android && bundle exec fastlane internal
