name: deploy tst

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - "v*"

jobs:
  build:
    runs-on: macos-14

    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2

      - name: Set up credentials
        run: |
          ./setup_credentials
          while read -r line; do echo "$line" >> $GITHUB_ENV; done < .env

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Set up fastlane
        run: |
          gem install bundler
          cd android && bundle install
          cd ..
          cd ios && bundle install

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Validate service account key (for Google Play Android Developer)
        working-directory: android
        run: bundle exec fastlane run validate_play_store_json_key json_key:"$GOOGLE_PLAY_JSON_KEY_PATH"

      - name: fastlane ios distribute
        working-directory: ios
        run: bundle exec fastlane distribute

      - name: fastlane android distribute
        working-directory: android
        run: bundle exec fastlane distribute
