name: prepare

on:
  workflow_dispatch:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: rubocop
        run: |
          cd fastlane
          bundle install
          bundle exec rubocop
